---
name: VyOS Equuleus (LTS) Release

on:
  workflow_dispatch:

env:
  SRC_REPO_URL: https://github.com/vyos/vyos-build
  BRANCH: equuleus
  ARCH: amd64
  BUILD_TYPE: release
  VERSION: 1.3-equuleus-lts
  DEBIAN_MIRROR: http://ftp.us.debian.org/debian/

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: vyos/vyos-build:equuleus
      options: --workdir /vyos --privileged
    steps:
      - name: Setup variables
        id: vars
        run: |
          build_date=$(date +%Y%m%d%H%M)
          echo "tag-name=${{ env.VERSION }}-${build_date}" >> "$GITHUB_OUTPUT"
          echo "iso-name=${{ env.VERSION }}-${build_date}-${{ env.ARCH }}" >> "$GITHUB_OUTPUT"

      - name: Clone source code
        run: git clone -b $BRANCH --single-branch $SRC_REPO_URL

      - name: Download sops deb
        uses: robinraju/release-downloader@768b85c8d69164800db5fc00337ab917daf3ce68 # v1.7
        with:
          repository: mozilla/sops
          latest: true
          fileName: "*amd64.deb"
          out-file-path: vyos-build/packages

      - name: Build ISO
        working-directory: ./vyos-build
        run: |
          sudo ./configure --architecture $ARCH \
            --build-type $BUILD_TYPE \
            --version $VERSION-$(date +%Y%m%d%H%M) \
            --custom-package "age" \
            --custom-package "git" \
            --custom-package "jq"
          sudo make iso
          mv ./build/live-image-$ARCH.hybrid.iso ./build/vyos-${{ steps.vars.outputs.iso-name }}.iso

      - name: Create release with artifact
        uses: ncipollo/release-action@a2e71bdd4e7dab70ca26a852f29600c98b33153e # v1
        with:
          tag: "v${{ steps.vars.outputs.tag-name }}"
          artifacts: "./vyos-build/build/vyos-${{ steps.vars.outputs.iso-name }}.iso"
          artifactErrorsFailBuild: true
          body: |
            Official VyOS Changelog:
            https://docs.vyos.io/en/latest/changelog/1.3.html
